name: Recovery Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cleanup
        uses: rokibhasansagar/slimhub_dot_files@main

      - name: Prepare the environment
        run: |
          sudo apt-get update || true
          sudo apt-get install -y git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 x11proto-core-dev libx11-dev libgl1-mesa-dev libxml2-utils xsltproc unzip bc libncurses5-dev python3-pip || true
          sudo apt-get install -y python-is-python3 || sudo ln -sf /usr/bin/python3 /usr/bin/python || true

      - name: Install OpenJDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Install repo
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo

      - name: Initialize and Sync
        run: |
          export PATH=~/bin:$PATH
          repo init --depth=1 -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp.git -b android-12.1
          repo sync -j$(nproc --all) --force-sync

      - name: Clone device tree
        run: |
          git clone https://github.com/Shahed420/Infinix_X6725B -b android-12.1 device/generic/X6725B

      - name: Build
        run: |
          export PATH=~/bin:$PATH
          source build/envsetup.sh
          lunch twrp_X6725B-eng || lunch omni_X6725B-eng
          make vendor_bootimage -j$(nproc --all)

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: TWRP-Recovery
          path: out/target/product/X6725B/vendor_boot.img
